name: f3dasm_env
channels:
  - gpytorch
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=1.3.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py310h5764c6d_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - algopy=0.5.7=py_0
  - ampl-mp=3.1.0=h2cc385e_1006
  - anyio=3.6.2=pyhd8ed1ab_0
  - aom=3.5.0=h27087fc_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h5764c6d_3
  - asttokens=2.0.8=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - autograd=1.5=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - black=22.10.0=py310hff52083_2
  - blas=1.0=mkl
  - bleach=5.0.1=pyhd8ed1ab_0
  - blinker=1.5=pyhd8ed1ab_0
  - boost-cpp=1.78.0=h75c5d50_1
  - botorch=0.7.3=0
  - brotlipy=0.7.0=py310h5764c6d_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_2
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py310hff52083_1
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - coverage=6.5.0=py310h5764c6d_1
  - cpuonly=2.0=0
  - cryptography=38.0.2=py310h597c629_1
  - debugpy=1.6.3=py310hd8f1fbe_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.0.0rc9=pyhd8ed1ab_0
  - executing=1.1.1=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - ffmpeg=5.1.2=gpl_hc51e5dc_103
  - flatbuffers=2.0.7=h27087fc_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=hc2a2eb6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hca18f0e_0
  - frozenlist=1.3.1=py310h5764c6d_0
  - future=0.18.2=py310hff52083_5
  - gast=0.4.0=pyh9f0ad1d_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.7.8=hf3e180e_0
  - google-auth=2.13.0=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.47.1=h05bd8bd_6
  - grpcio=1.47.1=py310h5b20944_6
  - h5py=3.7.0=nompi_py310h416281c_101
  - hdf5=1.12.2=nompi_h2386368_100
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py310hff52083_0
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ipopt=3.14.10=hf60ba86_0
  - ipykernel=6.16.2=pyh210e3f2_0
  - ipyparallel=8.4.1=pyhd8ed1ab_0
  - ipython=8.5.0=pyh41d4057_1
  - ipython_genutils=0.2.0=py_1
  - jax=0.3.24=pyhd8ed1ab_0
  - jaxlib=0.3.22=cpu_py310hb359a59_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.17.0=pyhd8ed1ab_0
  - jupyter_client=7.4.4=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py310hff52083_0
  - jupyter_server=1.23.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - keras=2.10.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h48a1fff_4
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcurl=7.85.0=h7bff187_0
  - libdeflate=1.14=h166bdaf_0
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - liblapack=3.9.0=16_linux64_mkl
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.38=h753d276_0
  - libprotobuf=3.21.8=h6239696_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.39.4=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.4.0=h55922b4_4
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libva=2.16.0=h166bdaf_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - linear_operator=0.2.0=0
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h5764c6d_2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - metis=5.1.0=h58526e2_1006
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2022.1.0=hc2b9512_224
  - multidict=6.0.2=py310h5764c6d_1
  - multipledispatch=0.6.0=py_0
  - multiprocess=0.70.14=py310h5764c6d_0
  - mumps-include=5.2.1=ha770c72_11
  - mumps-seq=5.2.1=h2104b81_11
  - mypy_extensions=0.4.3=py310hff52083_6
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.0=pyhd8ed1ab_0
  - nbconvert=7.2.4=pyhd8ed1ab_0
  - nbconvert-core=7.2.4=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.4=pyhd8ed1ab_0
  - nbformat=5.7.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.8.1=hc379101_1
  - networkx=2.8.7=pyhd8ed1ab_0
  - nlopt=2.7.1=py310h3342525_1
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - numdifftools=0.9.39=py_0
  - numpy=1.23.4=py310h53a5b5f_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openh264=2.3.1=h27087fc_1
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1s=h166bdaf_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=21.3=pyhd8ed1ab_0
  - pagmo=2.18.0=h69b656a_6
  - pandas=1.5.1=py310h769672d_1
  - pandoc=2.19.2=h32600fe_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathos=0.3.0=pyhd8ed1ab_0
  - pathspec=0.10.2=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py310h454ad03_3
  - pip=22.3=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - pluggy=1.0.0=py310hff52083_3
  - pox=0.3.2=pyhd8ed1ab_0
  - ppft=1.7.6.6=pyhd8ed1ab_0
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - protobuf=4.21.8=py310hd8f1fbe_0
  - psutil=5.9.3=py310h5764c6d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pygmo=2.18.0=py310h0fceb1a_3
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyro-api=0.1.2=pyhd8ed1ab_0
  - pyro-ppl=1.8.2=pyhd8ed1ab_0
  - pyrsistent=0.19.2=py310h5764c6d_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.2.0=py310hff52083_0
  - pytest-cov=4.0.0=pyhd8ed1ab_0
  - python=3.10.6=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-flatbuffers=2.0=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=1.13.0=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2022.5=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=24.0.1=py310h330234f_0
  - re2=2022.06.01=h27087fc_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=1.1.3=py310h0c3af53_1
  - scipy=1.9.3=py310hdfbd76f_2
  - scotch=6.0.9=hb2e6521_2
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - stack_data=0.5.1=pyhd8ed1ab_0
  - statsmodels=0.13.2=py310hde88566_0
  - svt-av1=1.3.0=h27087fc_0
  - tbb=2021.6.0=h924138e_0
  - tensorboard=2.10.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py310h597c629_2
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.10.0=cpu_py310hd1aba9c_0
  - tensorflow-base=2.10.0=cpu_py310hc537a0e_0
  - tensorflow-estimator=2.10.0=cpu_py310had6d012_0
  - termcolor=2.0.1=pyhd8ed1ab_1
  - terminado=0.17.0=pyh41d4057_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=0.13.0=py310_cpu
  - torchvision=0.14.0=py310_cpu
  - tornado=6.2=py310h5764c6d_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.5.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022e=h191b570_0
  - unixodbc=2.3.10=h583eb01_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.14.1=py310h5764c6d_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yarl=1.7.2=py310h5764c6d_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.10.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h6239696_4
  - pip:
    - alabaster==0.7.12
    - antlr4-python3-runtime==4.9.3
    - babel==2.11.0
    - contourpy==1.0.5
    - cycler==0.11.0
    - cython==0.29.32
    - docutils==0.17.1
    - emcee==3.1.3
    - emukit==0.4.9
    - flake8==5.0.4
    - fonttools==4.38.0
    - gpy==1.10.0
    - gpyopt==1.2.6
    - gpytorch==1.9.0
    - hydra-core==1.2.0
    - hypothesis==6.56.3
    - imagesize==1.4.1
    - kiwisolver==1.4.4
    - linear-operator==0.2.0
    - matplotlib==3.6.1
    - mccabe==0.7.0
    - omegaconf==2.2.3
    - paramz==0.9.5
    - plotly==5.11.0
    - pycodestyle==2.9.1
    - pyflakes==2.5.0
    - salib==1.4.6.1
    - snowballstemmer==2.2.0
    - sortedcontainers==2.4.0
    - sphinx==5.3.0
    - sphinx-autodoc-defaultargs==0.1.2
    - sphinx-autodoc-typehints==1.19.5
    - sphinx-rtd-theme==1.1.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - tenacity==8.1.0
prefix: /home/martin/miniconda3/envs/f3dasm_env
