name: f3dasm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20211102.0=h93e1e8c_2
  - absl-py=1.2.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py310h5764c6d_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - alabaster=0.7.12=py_0
  - algopy=0.5.7=py_0
  - alsa-lib=1.2.6.1=h7f98852_0
  - ampl-mp=3.1.0=h2cc385e_1006
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h5764c6d_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=22.1.0=pyh71513ae_1
  - autograd=1.4=pyhd8ed1ab_0
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - black=22.6.0=py310hff52083_2
  - bleach=5.0.1=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - bokeh=2.4.3=pyhd8ed1ab_3
  - boost-cpp=1.74.0=h75c5d50_8
  - bottleneck=1.3.5=py310hde88566_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h5764c6d_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.2.0=pyhd8ed1ab_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_0
  - cftime=1.6.2=py310hde88566_0
  - chardet=5.0.0=py310hff52083_0
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - click=8.1.3=py310hff52083_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - conda=4.13.0=py310hff52083_1
  - conda-build=3.22.0=py310hff52083_1
  - conda-package-handling=1.8.1=py310h5764c6d_1
  - coverage=6.4.3=py310h5764c6d_0
  - cryptography=37.0.4=py310h597c629_0
  - curl=7.83.1=h7bff187_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py310h5764c6d_0
  - dask=2022.2.1=pyhd3eb1b0_0
  - dask-core=2022.2.1=pyhd3eb1b0_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.0=py310hd8f1fbe_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.5.1=pyhd8ed1ab_0
  - distlib=0.3.5=pyhd8ed1ab_0
  - distributed=2022.2.1=pyhd3eb1b0_0
  - docutils=0.19=py310hff52083_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.9.1=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - fftw=3.3.10=nompi_ha7695d1_103
  - filelock=3.8.0=pyhd8ed1ab_0
  - flake8=5.0.4=pyhd8ed1ab_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.34.4=py310h5764c6d_0
  - freetype=2.10.4=hca18f0e_2
  - frozenlist=1.3.1=py310h5764c6d_0
  - fsspec=2022.8.2=pyhd8ed1ab_0
  - future=0.18.2=py310hff52083_5
  - gast=0.4.0=pyh9f0ad1d_0
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.72.1=h6239696_0
  - glib-tools=2.72.1=h6239696_0
  - glob2=0.7=py_0
  - google-auth=2.12.0=pyh1a96a4e_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - gpy=1.10.0=py310h96516ba_2
  - gpyopt=1.2.6=pyh8c360ce_0
  - grpc-cpp=1.46.4=h6fc47f4_3
  - grpcio=1.46.4=py310he36eabb_3
  - gst-plugins-base=1.20.3=hf6a322e_0
  - gstreamer=1.20.3=hd4edc92_0
  - h5py=3.7.0=nompi_py310h416281c_101
  - hdf4=4.2.15=h9772cbc_4
  - hdf5=1.12.2=nompi_h2386368_100
  - heapdict=1.0.1=py_0
  - hypothesis=6.29.3=pyhd3eb1b0_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py310hff52083_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipopt=3.14.7=hc8a599a_1
  - ipykernel=6.15.1=pyh210e3f2_0
  - ipyparallel=8.4.1=pyhd8ed1ab_0
  - ipython=8.4.0=py310hff52083_0
  - ipython_genutils=0.2.0=py_1
  - jack=1.9.18=h8c3723f_1002
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_2
  - jsonschema=4.15.0=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py310hff52083_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - keras=2.9.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_0
  - krb5=1.19.3=h3790be6_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libabseil=20211102.0=cxx17_h48a1fff_2
  - libarchive=3.5.2=hb890918_3
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcap=2.64=ha37c62d_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=14.0.6=default_h2e3cab8_0
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcups=2.3.3=hf5a7f15_1
  - libcurl=7.83.1=h7bff187_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.72.1=h2d90d5f_0
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblief=0.12.1=h27087fc_0
  - libllvm14=14.0.6=he0ac6c6_0
  - libnetcdf=4.8.1=nompi_h21705cb_104
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h753d276_3
  - libpq=14.5=hd77ab85_0
  - libprotobuf=3.20.1=h6239696_4
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h0e0dad5_3
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=249=h166bdaf_4
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.3=h522a892_1
  - libwebp-base=1.2.3=h166bdaf_2
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_3
  - libxslt=1.1.35=h8affb1d_0
  - libzip=1.9.2=hc869a4a_1
  - libzlib=1.2.12=h166bdaf_2
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=4.9.1=py310h5764c6d_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h5764c6d_1
  - matplotlib=3.5.2=py310hff52083_1
  - matplotlib-base=3.5.2=py310h5701ce4_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - metis=5.1.0=h58526e2_1006
  - mistune=2.0.4=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py310hbf28c38_0
  - multidict=6.0.2=py310h5764c6d_1
  - multiprocess=0.70.13=py310h5764c6d_1
  - mumps-include=5.2.1=ha770c72_11
  - mumps-seq=5.2.1=h2104b81_11
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy=0.971=py310h5764c6d_0
  - mypy_extensions=0.4.3=py310hff52083_5
  - mysql-common=8.0.30=haf5c9bc_0
  - mysql-libs=8.0.30=h28c427c_0
  - nbclient=0.6.7=pyhd8ed1ab_0
  - nbconvert=7.0.0=pyhd8ed1ab_0
  - nbconvert-core=7.0.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.0.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - netcdf4=1.6.1=nompi_py310h55e1e36_100
  - networkx=2.8.5=pyhd8ed1ab_0
  - nlopt=2.7.1=py310h3342525_1
  - notebook=6.4.12=pyha770c72_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numdifftools=0.9.39=py_0
  - numpy=1.23.1=py310h53a5b5f_0
  - oauthlib=3.2.1=pyhd8ed1ab_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1q=h166bdaf_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - packaging=21.3=pyhd8ed1ab_0
  - pagmo=2.18.0=hf227201_1
  - pandas=1.4.3=py310h769672d_0
  - pandoc=2.19.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramz=0.9.5=py_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.3.0=pyhd8ed1ab_0
  - patch=2.7.6=h7f98852_1002
  - patchelf=0.15.0=h58526e2_0
  - pathos=0.2.9=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py310he619898_0
  - pip=22.2.2=pyhd8ed1ab_0
  - pkginfo=1.8.3=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - pluggy=1.0.0=py310hff52083_3
  - ply=3.11=py_1
  - portaudio=19.6.0=h57a0ea0_5
  - pox=0.3.1=pyhd8ed1ab_0
  - ppft=1.7.6.5=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - protobuf=3.20.1=py310hd8f1fbe_0
  - psutil=5.9.1=py310h5764c6d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=14.0=h7f54b18_8
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py=1.11.0=pyh6c4a22f_0
  - py-lief=0.12.1=py310hd8f1fbe_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybind11-abi=4=hd8ed1ab_3
  - pybtex=0.24.0=pyhd8ed1ab_2
  - pybtex-docutils=1.0.2=py310hff52083_1
  - pycodestyle=2.9.1=pyhd8ed1ab_0
  - pycosat=0.6.3=py310h5764c6d_1010
  - pycparser=2.21=pyhd8ed1ab_0
  - pyflakes=2.5.0=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pygmo=2.18.0=py310h532db59_1
  - pyjwt=2.5.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py310h29803b5_0
  - pyqt5-sip=12.11.0=py310hd8f1fbe_0
  - pyrsistent=0.18.1=py310h5764c6d_1
  - pysocks=1.7.1=py310hff52083_5
  - pytest=7.1.2=py310hff52083_0
  - pytest-cov=3.0.0=pyhd8ed1ab_0
  - python=3.10.5=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
  - python-flatbuffers=1.12=pyhd8ed1ab_1
  - python-libarchive-c=4.0=py310hff52083_1
  - python_abi=3.10=2_cp310
  - pytz=2022.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py310h5764c6d_4
  - pyzmq=23.2.0=py310h330234f_0
  - qt-main=5.15.4=ha5833f6_2
  - re2=2022.06.01=h27087fc_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - ripgrep=13.0.0=h2f28480_2
  - rsa=4.9=pyhd8ed1ab_0
  - ruamel_yaml=0.15.80=py310h5764c6d_1007
  - salib=1.4.5=pyh6c4a22f_0
  - scienceplots=1.0.9=pyhd8ed1ab_2
  - scipy=1.9.0=py310hdfbd76f_0
  - scotch=6.0.9=hb2e6521_2
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=64.0.0=py310hff52083_0
  - sip=6.6.2=py310hd8f1fbe_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_1
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sphinx=5.1.1=pyhd8ed1ab_1
  - sphinx_rtd_theme=0.5.2=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-bibtex=2.4.2=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - sqlite=3.39.2=h4ff8645_0
  - stack_data=0.3.0=pyhd8ed1ab_0
  - statsmodels=0.13.2=py310hde88566_0
  - tbb=2021.5.0=h924138e_1
  - tblib=1.7.0=pyhd8ed1ab_0
  - tensorboard=2.9.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py310h597c629_2
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.9.1=cpu_py310hd1aba9c_0
  - tensorflow-base=2.9.1=cpu_py310h8df3ab6_0
  - tensorflow-estimator=2.9.1=cpu_py310had6d012_0
  - termcolor=2.0.1=pyhd8ed1ab_1
  - terminado=0.15.0=py310hff52083_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py310h5764c6d_0
  - tox=3.25.0=pyhd8ed1ab_0
  - tox-conda=0.9.2=pyhd8ed1ab_0
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typing-extensions=4.3.0=hd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022b=h191b570_0
  - unicodedata2=14.0.0=py310h5764c6d_1
  - unixodbc=2.3.10=h583eb01_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - virtualenv=20.16.3=py310hff52083_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.14.1=py310h5764c6d_0
  - xarray=2022.6.0=pyhd8ed1ab_1
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py310h5764c6d_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.5.2=h8a70e8d_3
  - pip:
    - antlr4-python3-runtime==4.9.3
    - commonmark==0.9.1
    - cython==0.29.32
    - f3dasm==0.1.9
    - hydra-core==1.2.0
    - jeepney==0.8.0
    - keyring==23.8.2
    - omegaconf==2.2.2
    - readme-renderer==36.0
    - requests-toolbelt==0.9.1
    - rfc3986==2.0.0
    - rich==12.5.1
    - secretstorage==3.3.3
    - torch==1.12.1
    - twine==4.0.1
    - webencodings==0.5.1
prefix: /home/martin/miniconda3/envs/f3dasm_env
