theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
        - content.code.copy
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        # logo: "material/circle-opacity"  # Logo in top left
    # favicon: "_static/favicon.png"
    # custom_dir: "docs/_overrides"  # Overriding part of the HTML

    # # These additions are my own custom ones, having overridden a partial.
    # twitter_bluesky_name: "@PatrickKidger"
    # twitter_url: "https://twitter.com/PatrickKidger"
    # bluesky_url: "https://PatrickKidger.bsky.social"

site_name: f3dasm
site_description: The documentation for the f3dasm library.
site_author: Martin van der Schelling
site_url: https://f3dasm.readthedocs.io/en/latest/

repo_url: https://github.com/bessagroup/f3dasm
repo_name: bessagroup/f3dasm
edit_uri: ""

strict: true  # Don't allow warnings during the build process

extra_javascript: 
    # The below two make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - _static/custom_css.css

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "Â¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4
    - footnotes

plugins:
    - search:
        # See https://github.com/squidfunk/mkdocs-material/discussions/8116#discussioncomment-12632752
        # and https://github.com/patrick-kidger/equinox/issues/984
        # In particular this allows for searching e.g. 'filter_grad' and to match 'equinox.filter_grad'.
        separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    - include_exclude_files:
        exclude:
            - "_overrides"
    - ipynb
    - mkdocstrings:
        handlers:
            python:
                paths: [src]
                options:
                    docstring_style: numpy
                    force_inspection: true
                    heading_level: 4
                    inherited_members: true
                    members_order: source
                    show_bases: false
                    show_if_no_docstring: true
                    show_overloads: false
                    show_root_heading: true
                    show_signature_annotations: true
                    show_source: true
                    show_symbol_type_heading: true
                    show_symbol_type_toc: true
                    filters:
                        - "!^__.*__$"  # Exclude dunder methods

nav:
    - 'index.md'
    - Getting started:
        - 'overview.md'
        - 'installation.md'
        - 'studies.md'
    - Tutorials:
        - Design-of-experiments:
            - 'notebooks/design/domain_creation.ipynb'
        - Managing experiments:
            - 'notebooks/experimentdata/experimentdata.ipynb'
        - Data-driven process:
            - 'notebooks/data-driven/blocks.ipynb'
            - 'notebooks/data-driven/carstoppingdistance.ipynb'
            - 'notebooks/data-driven/cluster.ipynb'
            - 'notebooks/data-driven/gridsampler.ipynb'
        - Built-in implementations:
            - 'notebooks/builtins/builtinfunction.ipynb'
            - 'notebooks/builtins/builtinoptimizers.ipynb'
            - 'notebooks/builtins/builtinsamplers.ipynb'
        - Integration with 3rd party libraries:
            - 'notebooks/integration/implement_optuna.ipynb'
            - 'notebooks/integration/implement_scipy.ipynb'
            - 'notebooks/hydra/usehydra.ipynb'
        - defaults.md
    - API Reference:
        - 'api/design.md'
        - 'api/experimentdata.md'
        - 'api/datageneration.md'
        - 'api/defaults.md'
        - 'api/hydra_tools.md'
    - License:
        - 'license.md'