design:
  lower_bound: -1.0
  upper_bound: 1.0
  dimensionality_lower_bound: 2
  dimensionality_upper_bound: 5

function:
  noise: None

optimizers:
  optimizers_names: [
    Adam,
    SGD,
    CG,
    CMAES,
    DifferentialEvolution,
    DualAnnealing,
    LBFGSB,
    NelderMead,
    PSO,
    RandomSearch,
    SGA,
    XNES,
    RMSprop,
    Nadam,
    Adamax,
    Ftrl,
  ]

sampler:
  sampler_name: RandomUniformSampling
  number_of_samples: 30

execution:
  number_of_functions: 10
  iterations: 500
  realizations: 10
  parallelization: True