name: release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: patrick-kidger/action_update_python_project@v8
        with:
          python-version: "3.11"
          test-script: |
            cp -r ${{ github.workspace }}/tests ./tests
            cp ${{ github.workspace }}/pyproject.toml ./pyproject.toml
            uv sync --extra test,all --no-install-project --inexact
            uv run --no-sync pytest
          pypi-token: ${{ secrets.pypi_api_token }}
          github-user: bessagroup
          github-token: ${{ github.token }}
