name: Pull request automated checks

on:
  pull_request:
    branches:
      - main
      - "pr/**"

jobs:
  check-coding-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip" # caching pip dependencies
      - name: Install Flake8 dependencies
        run: python -m pip install -U flake8
      - name: Run Flake8
        run: flake8 .
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip" # caching pip dependencies
      - name: Install test dependencies
        run: pip install -r tests/requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest (excluding abaqus tests)
        run: |
          python -m pytest -S abaqus
  build-sphinx-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip" # caching pip dependencies
      - name: Install package requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Sphinx
        run: python -m pip install -U sphinx
      - name: Install Sphinx requirements
        run: |
          pip install -r docs/requirements.txt
      - name: Build documentation
        run: |
          sphinx-build -b html ./docs ./docs/_build/html
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip" # caching pip dependencies
      - name: Install build dependencies
        run: python -m pip install -U setuptools wheel build
      - name: Build the package
        run: python -m build .
